name: Deploy to AWS
# Se ejecutará solo cuando hagas push a la rama 'test' Cambio
on:
  push:
    branches:
      - test  # Se ejecutará solo cuando hagas push a la rama 'test' Cambio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-updatecustomer:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-updatecustomer:latest

      - name: Conectar a AWS EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop updatecustomer || true
            sudo docker rm updatecustomer || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-updatecustomer:latest
            sudo docker run -d -p 5000:5000 --name updatecustomer --env-file /home/ubuntu/update_customer_service/.env ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-updatecustomer:latest
